[toolchain]
anchor_version = "0.32.1"
solana_version = "3.1.14"
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[test]
startup_wait = 20000

[programs.devnet]
carechain = "2M14a3k2cbSVqAkViKMfVEqndLWESHwNTwCHRYD66PwY"
priority_queue = "GB7xr669643BvgwmoDJwCEKFXWN252ECQtq3G2MhaENr"
yield_vault = "AEDNejZqKMWRXPp8E2mtqmeBooNAr4rtkEN5mdAbv8Tp"

[programs.localnet]
carechain = "2M14a3k2cbSVqAkViKMfVEqndLWESHwNTwCHRYD66PwY"
priority_queue = "GB7xr669643BvgwmoDJwCEKFXWN252ECQtq3G2MhaENr"
yield_vault = "AEDNejZqKMWRXPp8E2mtqmeBooNAr4rtkEN5mdAbv8Tp"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[test.validator]
url = "https://api.mainnet-beta.solana.com"
bind_address = "127.0.0.1"
rpc_port = 8899
faucet_port = 9901
gossip_port = 8001

[[test.validator.clone]]
address = "metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/*.ts"
